[project]
name = "loan-agnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.4",
    "langchain[openai]>=1.0.1",
    "langgraph>=1.0.1",
    "streamlit>=1.50.0",
]
